package com.entity;
// Generated 2017-3-27 12:11:26 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Active generated by hbm2java
 */
@Entity
@Table(name = "active", catalog = "oasys")
public class Active implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer activeId;
	private String activeName;
	private String activeInfo;
	private int activeAgreeNum;
	private Set<Activeinfo> activeinfos = new HashSet<Activeinfo>(0);

	public Active() {
	}

	public Active(String activeName, int activeAgreeNum) {
		this.activeName = activeName;
		this.activeAgreeNum = activeAgreeNum;
	}

	public Active(String activeName, String activeInfo, int activeAgreeNum, Set<Activeinfo> activeinfos) {
		this.activeName = activeName;
		this.activeInfo = activeInfo;
		this.activeAgreeNum = activeAgreeNum;
		this.activeinfos = activeinfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "activeID", unique = true, nullable = false)
	public Integer getActiveId() {
		return this.activeId;
	}

	public void setActiveId(Integer activeId) {
		this.activeId = activeId;
	}

	@Column(name = "activeName", nullable = false, length = 50)
	public String getActiveName() {
		return this.activeName;
	}

	public void setActiveName(String activeName) {
		this.activeName = activeName;
	}

	@Column(name = "activeInfo", length = 10)
	public String getActiveInfo() {
		return this.activeInfo;
	}

	public void setActiveInfo(String activeInfo) {
		this.activeInfo = activeInfo;
	}

	@Column(name = "activeAgreeNum", nullable = false)
	public int getActiveAgreeNum() {
		return this.activeAgreeNum;
	}

	public void setActiveAgreeNum(int activeAgreeNum) {
		this.activeAgreeNum = activeAgreeNum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "active")
	public Set<Activeinfo> getActiveinfos() {
		return this.activeinfos;
	}

	public void setActiveinfos(Set<Activeinfo> activeinfos) {
		this.activeinfos = activeinfos;
	}

}
