package com.entity;
// Generated 2017-3-27 12:11:26 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Dept generated by hbm2java
 */
@Entity
@Table(name = "dept", catalog = "oasys")
public class Dept implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int deptId;
	private String deptName;
	private String deptText;
	private Set<Employees> employeeses = new HashSet<Employees>(0);
	private Set<Job> jobs = new HashSet<Job>(0);

	public Dept() {
	}

	public Dept(int deptId, String deptName) {
		this.deptId = deptId;
		this.deptName = deptName;
	}

	public Dept(int deptId, String deptName, String deptText, Set<Employees> employeeses, Set<Job> jobs) {
		this.deptId = deptId;
		this.deptName = deptName;
		this.deptText = deptText;
		this.employeeses = employeeses;
		this.jobs = jobs;
	}

	@Id
	@Column(name = "deptID", unique = true, nullable = false)
	public int getDeptId() {
		return this.deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}

	@Column(name = "deptName", length = 50)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "deptText", length = 50)
	public String getDeptText() {
		return this.deptText;
	}

	public void setDeptText(String deptText) {
		this.deptText = deptText;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "dept")
	@JsonIgnore
	public Set<Employees> getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set<Employees> employeeses) {
		this.employeeses = employeeses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "dept")
	@JsonIgnore
	public Set<Job> getJobs() {
		return this.jobs;
	}

	public void setJobs(Set<Job> jobs) {
		this.jobs = jobs;
	}

}
