package com.entity;
// Generated 2017-3-27 12:11:26 by Hibernate Tools 3.5.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name = "file", catalog = "oasys")
public class File implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer fileId;
	private Employees employeesByFileTo;
	private Employees employeesByFileFrom;
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date fileTime;
	private String fileText;
	private String fileName;

	public File() {
	}

	public File(Employees employeesByFileTo, Employees employeesByFileFrom, Date fileTime, String fileText,
			String fileName) {
		this.employeesByFileTo = employeesByFileTo;
		this.employeesByFileFrom = employeesByFileFrom;
		this.fileTime = fileTime;
		this.fileText = fileText;
		this.fileName = fileName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "fileID", unique = true, nullable = false)
	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fileTo")
	public Employees getEmployeesByFileTo() {
		return this.employeesByFileTo;
	}

	public void setEmployeesByFileTo(Employees employeesByFileTo) {
		this.employeesByFileTo = employeesByFileTo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "fileFrom")
	public Employees getEmployeesByFileFrom() {
		return this.employeesByFileFrom;
	}

	public void setEmployeesByFileFrom(Employees employeesByFileFrom) {
		this.employeesByFileFrom = employeesByFileFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fileTime", length = 19)
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	public Date getFileTime() {
		return this.fileTime;
	}

	public void setFileTime(Date fileTime) {
		this.fileTime = fileTime;
	}

	@Column(name = "fileText", length = 50)
	public String getFileText() {
		return this.fileText;
	}

	public void setFileText(String fileText) {
		this.fileText = fileText;
	}

	@Column(name = "fileName", length = 50)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

}
