package com.entity;
// Generated 2017-3-27 12:11:26 by Hibernate Tools 3.5.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "task", catalog = "oasys")
public class Task implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer taskId;
	private Employees employees;
	private String taskName;
	private String taskInfo;
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date getTime;
	private String taskState;

	public Task() {
	}

	public Task(Employees employees, String taskName, String taskInfo, Date getTime, String taskState) {
		this.employees = employees;
		this.taskName = taskName;
		this.taskInfo = taskInfo;
		this.getTime = getTime;
		this.taskState = taskState;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "taskID", unique = true, nullable = false)
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "employeeID")
	@JsonIgnore
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@Column(name = "taskName", length = 50)
	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "taskInfo", length = 65535)
	public String getTaskInfo() {
		return this.taskInfo;
	}

	public void setTaskInfo(String taskInfo) {
		this.taskInfo = taskInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "getTime", length = 19)
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	public Date getGetTime() {
		return this.getTime;
	}

	public void setGetTime(Date getTime) {
		this.getTime = getTime;
	}

	@Column(name = "taskState", length = 50)
	public String getTaskState() {
		return this.taskState;
	}

	public void setTaskState(String taskState) {
		this.taskState = taskState;
	}

}
